//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Living.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Living
    {
        public int LiveId { get; set; }
        public int HouseId { get; set; }
        public int UserId { get; set; }
    }
}
