//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Living.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchHistory
    {
        public int SearchId { get; set; }
        public string SearchKey { get; set; }
        public System.DateTime SearchDate { get; set; }
    }
}
